name: Basic Workflow
on:
  workflow_dispatch:
jobs:
  basic-workflow-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Say hello
        run: echo "Hello from GitHub Actions!"
