name: Scheduler demo job
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
jobs:
  scheduler-every-5-minute:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "hello my friend...."
